services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otim-florist-app
    restart: unless-stopped
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      SERVER_NAME: ":80"
      INERTIA_SSR_URL: "http://ssr:13714"

  ssr:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["production"]
    volumes:
      - .:/app
    command: php artisan inertia:start-ssr
